import { Loan, Branch, BlogPost, Team } from '@/types/index';

export const LOAN_PRODUCTS: Loan[] = [
  {
    id: '1',
    name: 'Business Loans',
    description: 'Flexible funding for starting or expanding your business',
    minAmount: 500000,
    maxAmount: 50000000,
    interestRate: 15,
    tenureMonths: 36,
    icon: '🏢',
    benefits: [
      'Quick approval process',
      'Flexible repayment terms',
      'No collateral required',
      'Competitive interest rates',
    ],
    requirements: [
      'Business registration',
      'Tax compliance documents',
      'Business plan',
      'Bank statements (6 months)',
    ],
  },
  {
    id: '2',
    name: 'SME Financing',
    description: 'Tailored financing solutions for small and medium enterprises',
    minAmount: 1000000,
    maxAmount: 100000000,
    interestRate: 14,
    tenureMonths: 48,
    icon: '📊',
    benefits: [
      'Fast processing',
      'Extended repayment period',
      'Business mentorship',
      'Financial advisory',
    ],
    requirements: [
      'Business license',
      'Financial statements',
      'Proof of business operation',
      'Owner identification',
    ],
  },
  {
    id: '3',
    name: 'Agricultural Loans',
    description: 'Specialized financing for farmers and agricultural businesses',
    minAmount: 300000,
    maxAmount: 30000000,
    interestRate: 12,
    tenureMonths: 24,
    icon: '🌾',
    benefits: [
      'Seasonal repayment options',
      'Input supply partnerships',
      'Farmer training programs',
      'Market linkage support',
    ],
    requirements: [
      'Farm registration',
      'Land ownership proof',
      'Production records',
      'Farmer ID',
    ],
  },
  {
    id: '4',
    name: 'Emergency Loans',
    description: 'Quick funding for urgent financial needs',
    minAmount: 100000,
    maxAmount: 5000000,
    interestRate: 18,
    tenureMonths: 12,
    icon: '🆘',
    benefits: [
      '24-hour approval',
      'Minimal documentation',
      'Instant disbursement',
      'Easy application',
    ],
    requirements: [
      'Valid ID',
      'Phone number',
      'Employment verification',
      'Income proof',
    ],
  },
  {
    id: '5',
    name: 'Group Lending',
    description: 'Collective borrowing with mutual accountability',
    minAmount: 200000,
    maxAmount: 20000000,
    interestRate: 13,
    tenureMonths: 24,
    icon: '👥',
    benefits: [
      'Lower interest rates',
      'Group support system',
      'Flexible terms',
      'Community empowerment',
    ],
    requirements: [
      'Group registration',
      'Member list',
      'Group constitution',
      'Joint application',
    ],
  },
  {
    id: '6',
    name: 'Asset Financing',
    description: 'Finance equipment and machinery purchases',
    minAmount: 2000000,
    maxAmount: 200000000,
    interestRate: 11,
    tenureMonths: 60,
    icon: '🚜',
    benefits: [
      'Equipment ownership',
      'Extended tenure',
      'Supplier partnerships',
      'Maintenance support',
    ],
    requirements: [
      'Business license',
      'Equipment quotes',
      'Insurance policy',
      'Financial statements',
    ],
  },
];

export const BRANCHES: Branch[] = [
  {
    id: '1',
    name: 'Head Office',
    address: 'Plot 123, Business Park',
    city: 'Dar es Salaam',
    phone: '+255 22 XXX XXXX',
    email: 'info@bupekfinance.com',
    hours: 'Monday - Friday: 8:00 AM - 5:00 PM',
    latitude: -6.8,
    longitude: 39.28,
  },
  {
    id: '2',
    name: 'Arusha Branch',
    address: 'Plot 456, Industrial Area',
    city: 'Arusha',
    phone: '+255 27 XXX XXXX',
    email: 'arusha@bupekfinance.com',
    hours: 'Monday - Friday: 8:30 AM - 4:30 PM',
    latitude: -3.367,
    longitude: 36.68,
  },
  {
    id: '3',
    name: 'Mbeya Branch',
    address: 'Plot 789, City Center',
    city: 'Mbeya',
    phone: '+255 25 XXX XXXX',
    email: 'mbeya@bupekfinance.com',
    hours: 'Monday - Friday: 8:00 AM - 5:00 PM',
    latitude: -8.91,
    longitude: 33.45,
  },
];

export const BLOG_POSTS: BlogPost[] = [
  {
    id: '1',
    title: 'How to Grow Your Business with Right Financing',
    slug: 'grow-business-financing',
    excerpt: 'Learn the key strategies for using business loans effectively to scale your operations.',
    content: 'Full blog content here...',
    category: 'Business Growth',
    image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=600&h=400&fit=crop',
    author: 'John Doe',
    date: '2024-05-15',
    readTime: 5,
  },
  {
    id: '2',
    title: '5 Essential Tips for First-Time Entrepreneurs',
    slug: '5-tips-entrepreneurs',
    excerpt: 'Discover essential tips and tricks for launching your first business venture successfully.',
    content: 'Full blog content here...',
    category: 'Entrepreneurship',
    image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=600&h=400&fit=crop',
    author: 'Jane Smith',
    date: '2024-05-10',
    readTime: 7,
  },
  {
    id: '3',
    title: 'Digital Financial Inclusion in Tanzania',
    slug: 'financial-inclusion-tanzania',
    excerpt: 'Understanding the role of digital finance in advancing financial inclusion across the nation.',
    content: 'Full blog content here...',
    category: 'Financial Education',
    image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=600&h=400&fit=crop',
    author: 'Mike Johnson',
    date: '2024-05-05',
    readTime: 6,
  },
];

export const TEAM: Team[] = [
  {
    id: '1',
    name: 'Dr. Samuel Mwangi',
    position: 'Chief Executive Officer',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&h=300&fit=crop',
    bio: 'With over 15 years of experience in finance and microfinance, Dr. Mwangi leads BUPEK Finance with vision and expertise.',
  },
  {
    id: '2',
    name: 'Grace Mwangi',
    position: 'Chief Financial Officer',
    image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=300&h=300&fit=crop',
    bio: 'Grace brings strategic financial management and operational excellence to ensure sustainable growth.',
  },
  {
    id: '3',
    name: 'Peter Kimani',
    position: 'Head of Operations',
    image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&h=300&fit=crop',
    bio: 'Peter oversees all operational aspects with a focus on customer satisfaction and efficiency.',
  },
];

export const FAQ = [
  {
    id: '1',
    question: 'What is the minimum loan amount?',
    answer: 'The minimum loan amount varies depending on the type of loan. Emergency loans start from TZS 100,000, while business loans start from TZS 500,000.',
  },
  {
    id: '2',
    question: 'How long does loan approval take?',
    answer: 'Standard approval takes 3-5 business days. Emergency loans can be approved within 24 hours.',
  },
  {
    id: '3',
    question: 'What is the interest rate?',
    answer: 'Interest rates range from 11% to 18% depending on the loan type, amount, and repayment period.',
  },
  {
    id: '4',
    question: 'Do I need collateral?',
    answer: 'Most loans do not require collateral. Asset financing may require the asset as security.',
  },
  {
    id: '5',
    question: 'What documents are required?',
    answer: 'Required documents vary by loan type but typically include ID, business registration, bank statements, and proof of income.',
  },
  {
    id: '6',
    question: 'Can I repay my loan early?',
    answer: 'Yes, early repayment is encouraged with no penalties. You may save on interest charges.',
  },
];
